### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by Baikele** [Maplefsnow/MapCDK#1]
可以支持一下1.16.5的版本么？另外，支持创建可以永久使用的cdk么？一个人限制使用几次的那种

**Comment by Maplefsnow** [comment]
感谢你的提议，这确实是我漏掉的一个功能

预计在下个版本上线你期望的功能，请关注最新版本

**Comment by Maplefsnow** [comment]
创建永久 CDK 已经完工，将在最新版本发布

1.16.5 的远程仓库被papermc删掉了目前我找不到依赖项，需要帮助

一个人限制使用几次经过考虑后不予添加，因为CDK本身就是一次性产品，如有需要请创建多个相同的CDK

**Comment by Baikele** [comment]
> 创造永恒CDK 已完成工作，将在最新版本发布
> 
> 1.16.5的远程仓库被papermc削掉了目前我找不到依赖项，需要帮助
> 
> 一个人限制使用几次经过思考后不予添加，因为CDK本身就是一次性产品，如有需要请创建多个相同的CDK

好的，感谢

**Comment by Baikele** [comment]
> papermc

可以直接使用spigot的啊，为什么要paper的？



    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

**Comment by Maplefsnow** [comment]
好的，感谢提醒

**Comment by Maplefsnow** [comment]
added on 0.3.0
