### ISSUE TITLE
功能请求[随机字符可以添加全部字符么？]

### ISSUE THREAD

**Issue by Baikele** [Maplefsnow/MapCDK#2]

**Comment by Maplefsnow** [comment]
我个人不是很喜欢带其他字符的cdk，看起来像乱码一样，不过如果你喜欢的话可以fork本仓库自己搓一个出来，很简单只需要改动一行代码

**Comment by Baikele** [comment]
> 我个人不是很喜欢带其他字符的cdk，看起来像乱码一样，不过如果你喜欢的话可以fork本仓库自己搓一个出来，很简单只需要改动一行代码

好的，那就等上个版本除了自己搓吧
