### ISSUE TITLE
mapcdk玩家使用问题

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Maplefsnow/MapCDK#4]
玩家在使用插件的时候出现了/mapcdk指令无效的问题，在我看来是权限问题，但是我给予了玩家mapcdk.cdk权限并没有效果，请问我需要做什么？
最后感谢你给予我的帮助

**Comment by Maplefsnow** [comment]
你好，感谢你的反馈

这个问题我已经在本地修复，明日将在GitHub发布最新发行版，请关注

**Comment by xiaoyueyoqwq** [comment]
> 你好，感谢你的反馈
> 
> 这个问题我已经在本地修复，明日将在GitHub发布最新发行版，请关注

我希望你没忘记要把更新文件拉进GitHub仓库🙃

**Comment by Maplefsnow** [comment]
呜呜，已经更新了
